-- Item 3
SELECT O.DESC_OPERACION AS Tipo,
    TO_CHAR(
        NVL(SUM(
            CASE 
                WHEN TPIVA.DESC_TIPO_IVA = 'IVA 10%' THEN DO.PRECIO_OPERACION
            END    
        ), 0)
    , '999G999G999') AS Monto_10,
    TO_CHAR(
        NVL(SUM(
            CASE 
                WHEN TPIVA.DESC_TIPO_IVA = 'IVA 10%' THEN DO.IMPORTE_IVA
            END    
        ), 0)
    ,'999G999G999') AS IVA_10,
    TO_CHAR(
        NVL(SUM(
            CASE 
                WHEN TPIVA.DESC_TIPO_IVA = 'IVA 5%' THEN DO.PRECIO_OPERACION
            END    
        ), 0)
    ,'999G999G999') AS Monto_5,
    TO_CHAR(NVL(SUM(
            CASE
                WHEN TPIVA.DESC_TIPO_IVA = 'IVA 5%' THEN DO.IMPORTE_IVA
            END
        ), 0)
    , '999G999G999') AS IVA_5
FROM  D_DETALLE_OPERACIONES DO
JOIN D_MOVIMIENTO_OPERACIONES DMO
    ON DO.ID_OPERACION = DMO.ID_OPERACION
JOIN D_TIPO_IVA TPIVA
    ON DO.COD_TIPO_IVA = TPIVA.COD_TIPO_IVA
JOIN D_OPERACIONES O
    ON DMO.COD_OPERACION = O.COD_OPERACION
WHERE DMO.TIPO_REGISTRO LIKE '%A%' 
    AND (O.DESC_OPERACION LIKE '%VENTA%'
    OR O.DESC_OPERACION LIKE '%COMPRA%')
GROUP BY O.DESC_OPERACION
ORDER BY O.DESC_OPERACION DESC;