-- Item 2
--INSERT INTO: D_ASIENTO_CABECERA
INSERT INTO D_ASIENTO_CABECERA (FECHA_ASIENTO, CONCEPTO)
VALUES (SYSDATE, 'CONTABLES');

INSERT INTO D_PLANTILLA_ASIENTO (NOMBRE, ACTIVA)
VALUES ('BASE CONTABLE', 'S');

-- DROPS
--1
DROP TABLE D_PLANTILLA_DETALLE;
--2 
DROP TABLE D_PLANTILLA_ASIENTO;
--3
DROP TABLE D_ASIENTO_DETALLE;
--4
DROP TABLE D_CUENTAS_CONTABLES
--5
DROP TABLE D_ASIENTO_CABECERA;
