
CREATE TABLE D_BANCO
(
	COD_BANCO            NUMBER(3) NOT NULL ,
	DESC_BANCO           VARCHAR2(80) NOT NULL ,
CONSTRAINT  PKd_banco PRIMARY KEY (COD_BANCO)
);



COMMENT ON TABLE D_BANCO IS 'Tabla de Bancos';




COMMENT ON COLUMN D_BANCO.COD_BANCO IS 'Código de banco';




COMMENT ON COLUMN D_BANCO.DESC_BANCO IS 'Descripción del banco';



CREATE TABLE D_BANCO_CUENTA
(
	COD_BANCO            NUMBER(3) NOT NULL ,
	NRO_CUENTA           VARCHAR2(20) NOT NULL ,
	SALDO_ACTUAL         NUMBER(15) NOT NULL ,
CONSTRAINT  PKd_banco_cuenta PRIMARY KEY (COD_BANCO,NRO_CUENTA)
);


COMMENT ON TABLE D_BANCO_CUENTA IS 'Tabla de cuentas bancarias de la empresa';

COMMENT ON COLUMN D_BANCO_CUENTA.COD_BANCO IS 'Código de banco';


COMMENT ON COLUMN D_BANCO_CUENTA.NRO_CUENTA IS 'Nro de la Cuenta';




COMMENT ON COLUMN D_BANCO_CUENTA.SALDO_ACTUAL IS 'Saldo actual de la cuenta';



CREATE TABLE D_CAJAS
(
	NRO_CAJA             NUMBER(2) NOT NULL ,
	DESC_CAJA            VARCHAR2(20) NULL ,
	NRO_TIMBRADO         NUMBER(12) NOT NULL ,
CONSTRAINT  PKd_cajas PRIMARY KEY (NRO_CAJA)
);



COMMENT ON TABLE D_CAJAS IS 'Tabla de Caja registradora de operaciones';




COMMENT ON COLUMN D_CAJAS.NRO_CAJA IS 'Nro de identificación de la Caja';




COMMENT ON COLUMN D_CAJAS.DESC_CAJA IS 'Descripción de la Caja';




COMMENT ON COLUMN D_CAJAS.NRO_TIMBRADO IS 'Nro de timbrado';



CREATE TABLE D_DETALLE_OPERACIONES
(   ID_REGISTRO          NUMBER(14) NOT NULL ,
	ID_OPERACION         NUMBER(12) NOT NULL ,
	ID_PRODUCTO          NUMBER(12) NOT NULL ,
	COD_MEDIDA           NUMBER(3) NOT NULL ,
	CANTIDAD_OPERACION   NUMBER(12,2) NOT NULL ,
	PRECIO_OPERACION     NUMBER(12) NOT NULL ,
	IMPORTE_OPERACION    NUMBER(12) NOT NULL ,
	IMPORTE_DESCUENTO    NUMBER(10) NOT NULL ,
	COD_TIPO_IVA         NUMBER(3) NOT NULL ,
	PORCENTAJE_IVA       NUMBER(3) NOT NULL ,
	IMPORTE_IVA          NUMBER(10) NOT NULL ,
	IMPORTE_RECARGO      NUMBER(10) NOT NULL ,
CONSTRAINT  PKd_detalle_operaciones PRIMARY KEY (ID_REGISTRO)
);



COMMENT ON TABLE D_DETALLE_OPERACIONES IS 'Tabla detalle de operaciónes';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.CANTIDAD_OPERACION IS 'Cantidad del producto, en la unidad de medida';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.PRECIO_OPERACION IS 'Precio del producto';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.IMPORTE_OPERACION IS 'Importe de la operacion: Determinado por el producto de cantidad_peracion por el precio_operacion';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.IMPORTE_DESCUENTO IS 'Importe de descuento applicado al producto, dependiente de la forma de pago';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.COD_TIPO_IVA IS 'Código de tipo de IVA';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.PORCENTAJE_IVA IS 'Porcentaje de IVA, aplicado al producto';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.IMPORTE_IVA IS 'Importe de iva, se obtiene del resultado de la división entre el ( importe_operacion + importe_recargo -importe descuento ) /divisor_iva_incluido, redondeado a cero decimales. Este ultimo se obtiene de la tabla d_tipo_iva, dependiendo del cod_tipo_iva';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.IMPORTE_RECARGO IS 'Importe de recargo applicado al producto, dependiente de la forma de pago';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.ID_PRODUCTO IS 'Identificador de Productos';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.COD_MEDIDA IS 'Codigo de media';




COMMENT ON COLUMN D_DETALLE_OPERACIONES.ID_OPERACION IS 'Nro de identificación de la operación';



CREATE TABLE D_FORMA_PAGO
(
	COD_FORMA_PAGO       NUMBER(2) NOT NULL ,
	DESC_FORMA_PAGO      VARCHAR2(20) NOT NULL ,
	REQUIERE_NRO_COMPROBANTE NUMBER(1) DEFAULT 0 NOT NULL ,
	PORCENTAJE_DESCUENTO NUMBER(7,2) NOT NULL ,
	PORCENTAJE_RECARGO   NUMBER(7,2) NOT NULL ,
CONSTRAINT  PKd_forma_pago PRIMARY KEY (COD_FORMA_PAGO)
);



COMMENT ON TABLE D_FORMA_PAGO IS 'Tabla de formas de pagos, admitdos en el sistema';




COMMENT ON COLUMN D_FORMA_PAGO.COD_FORMA_PAGO IS 'Código de forma de pago';




COMMENT ON COLUMN D_FORMA_PAGO.DESC_FORMA_PAGO IS 'Descripcón de la forma de pago';




COMMENT ON COLUMN D_FORMA_PAGO.REQUIERE_NRO_COMPROBANTE IS 'Campo que determina si la forma de pago requiere se asigne un numero de comprobante de la transaccion externa en el Post de pago: 0 = no, 1 = si';




COMMENT ON COLUMN D_FORMA_PAGO.PORCENTAJE_DESCUENTO IS 'Porcentaje de descuento que se obiene al pagar esta forma de pago-';




COMMENT ON COLUMN D_FORMA_PAGO.PORCENTAJE_RECARGO IS 'Porcentaje de recargo que se aplique al pagar en es ta forma de pago';



CREATE TABLE D_MEDIDA
(
	COD_MEDIDA           NUMBER(3) NOT NULL ,
	DESC_MEDIDA          VARCHAR2(30) NOT NULL ,
	CANT_UNIDADES        NUMBER(5) NULL ,
CONSTRAINT  PKd_medida PRIMARY KEY (COD_MEDIDA)
);



COMMENT ON TABLE D_MEDIDA IS 'Tabla de medidas';




COMMENT ON COLUMN D_MEDIDA.COD_MEDIDA IS 'Codigo de media';




COMMENT ON COLUMN D_MEDIDA.DESC_MEDIDA IS 'Descripcion de medida';




COMMENT ON COLUMN D_MEDIDA.CANT_UNIDADES IS 'Cantidad de unidades por medida';



CREATE TABLE D_MOVIMIENTO_OPERACIONES
(	ID_OPERACION         NUMBER(12) NOT NULL ,
	FECHA_OPERACION      DATE NOT NULL ,
	COD_SUCURSAL         NUMBER(2) NOT NULL ,
	COD_OPERACION        NUMBER(3) NOT NULL ,
	ID_PERSONA           NUMBER(10) NOT NULL ,
	NRO_CAJA             NUMBER(2) NULL ,
	ID_USUARIO           VARCHAR2(4) NOT NULL ,
	COD_TIPO_COMPROBANTE NUMBER(2) NOT NULL ,
	NRO_COMPROBANTE      VARCHAR2(20) NOT NULL ,
	TIPO_REGISTRO        CHAR(1) NOT NULL  CONSTRAINT  CHECK_TIPO_REGISTRO CHECK (tipo_registro IN ('A', 'E')),
	DESCRIPCION_OPERACION VARCHAR2(800) NULL ,
	NRO_TIMBRADO         NUMBER(12) NOT NULL ,
	FECHA_INSERT         DATE NOT NULL ,
CONSTRAINT  PKd_movimiento_operaciones PRIMARY KEY (ID_OPERACION)
);



COMMENT ON TABLE D_MOVIMIENTO_OPERACIONES IS 'Tabla cabecera de movimiento de operaciones';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.COD_OPERACION IS 'Código de operación';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.ID_PERSONA IS 'Identificador de la persona';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.NRO_CAJA IS 'Nro de identificación de la Caja';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.ID_USUARIO IS 'Identificador del Usuario del sistema';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.FECHA_INSERT IS 'Fecha del sistema';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.COD_TIPO_COMPROBANTE IS 'Código del tipo de comprobante';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.TIPO_REGISTRO IS 'Determina si el tipo de registro está o no anulado. Los valores posiblres son A, indica activo, E: eliminado';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.NRO_COMPROBANTE IS 'Nro de comprobante, dependiente del tipo de comprobante';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.NRO_TIMBRADO IS 'Nro de Timbrado';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.ID_OPERACION IS 'Nro de identificación de la operación';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.FECHA_OPERACION IS 'Fecha de la operción';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.COD_SUCURSAL IS 'Código de Sucursal';




COMMENT ON COLUMN D_MOVIMIENTO_OPERACIONES.DESCRIPCION_OPERACION IS 'Descripción de la operación';



CREATE TABLE D_OPERACIONES
(
	COD_OPERACION        NUMBER(3) NOT NULL ,
	DESC_OPERACION       VARCHAR2(50) NOT NULL ,
	USO_CAJERO           NUMERIC(1) NOT NULL ,
CONSTRAINT  PKd_operaciones PRIMARY KEY (COD_OPERACION)
);



COMMENT ON TABLE D_OPERACIONES IS 'Tabla de operaciones del sistema';




COMMENT ON COLUMN D_OPERACIONES.COD_OPERACION IS 'Código de operación';




COMMENT ON COLUMN D_OPERACIONES.DESC_OPERACION IS 'Descripcion de la operación';




COMMENT ON COLUMN D_OPERACIONES.USO_CAJERO IS 'Campo que determina si la operacion es de uso cajero, en caso que su valor es 1, la operación requiere emitir una factura, los datos se obtienen de la tabla d_timbrado, si es 0, debe obtener el valor del campo nro_comprobante_actual de la tabla d_ tipo comprobante';



CREATE TABLE D_PAGO_OPERACION
(	ID_REGISTRO          NUMBER(12) NOT NULL ,
	COD_FORMA_PAGO       NUMBER(2) NOT NULL ,
	NRO_REFERENCIA_PAGO  NUMBER(12) NULL ,
	COD_BANCO            NUMBER(3) NULL ,
	NRO_CUENTA           VARCHAR2(20) NULL ,
	NRO_CHEQUE           VARCHAR2(20) NULL ,
	IMPORTE_PAGO         NUMBER(12) NOT NULL ,
	ID_OPERACION         NUMBER(12) NOT NULL ,
CONSTRAINT  PKd_pago_operacion PRIMARY KEY (ID_REGISTRO)
);



COMMENT ON TABLE D_PAGO_OPERACION IS 'Tabla que registra el pago en cualquiera de las modalidades';


COMMENT ON COLUMN D_PAGO_OPERACION.COD_FORMA_PAGO IS 'Código de forma de pago';




COMMENT ON COLUMN D_PAGO_OPERACION.NRO_REFERENCIA_PAGO IS 'Nro de referencia del pago externo';




COMMENT ON COLUMN D_PAGO_OPERACION.COD_BANCO IS 'Código de banco';




COMMENT ON COLUMN D_PAGO_OPERACION.NRO_CUENTA IS 'Nro de Cuenta del banco';




COMMENT ON COLUMN D_PAGO_OPERACION.NRO_CHEQUE IS 'Nro de Cheque';




COMMENT ON COLUMN D_PAGO_OPERACION.IMPORTE_PAGO IS 'Importe del pago';




COMMENT ON COLUMN D_PAGO_OPERACION.ID_REGISTRO IS 'Identificador del registro, tipo identity';




COMMENT ON COLUMN D_PAGO_OPERACION.ID_OPERACION IS 'Nro de identificación de la operación';



CREATE TABLE D_PERSONAS
(
	ID_PERSONA           NUMBER(10) NOT NULL ,
	DENOMINACION         VARCHAR2(80) NOT NULL ,
	NRO_DOCUMENTO        NUMBER(12) NOT NULL ,
	RUC                  VARCHAR2(20) NULL ,
	EMAIL                VARCHAR2(20) NULL ,
	LOCALIDAD            VARCHAR2(20) NULL ,
	NRO_TELEFONO         VARCHAR2(40) NULL ,
CONSTRAINT  PKd_personas PRIMARY KEY (ID_PERSONA)
);



COMMENT ON TABLE D_PERSONAS IS 'Tabla de Personas';




COMMENT ON COLUMN D_PERSONAS.ID_PERSONA IS 'Identificador de la persona';




COMMENT ON COLUMN D_PERSONAS.DENOMINACION IS 'Denominación de la persona';




COMMENT ON COLUMN D_PERSONAS.NRO_DOCUMENTO IS 'Nro de documento de identeidad';




COMMENT ON COLUMN D_PERSONAS.RUC IS 'Nro de Ruc';




COMMENT ON COLUMN D_PERSONAS.EMAIL IS 'Emal';




COMMENT ON COLUMN D_PERSONAS.LOCALIDAD IS 'Localidad donde reside';




COMMENT ON COLUMN D_PERSONAS.NRO_TELEFONO IS 'Nro de telefono';



CREATE TABLE D_PRODUCTOS
(
	ID_PRODUCTO          NUMBER(12) NOT NULL ,
	DESC_PRODUCTO        VARCHAR2(80) NOT NULL ,
	COD_TIPO_PRODUCTO    NUMBER(5) NOT NULL ,
	COD_TIPO_IVA         NUMBER(3) NOT NULL ,
	CODIGO_BARRA         VARCHAR2(20) NULL ,
	PORCENTAJE_BENEFICIO NUMBER(7,2) NOT NULL ,
	DESC_ABREVIADO       VARCHAR2(20) NOT NULL ,
	FECHA_ULTIMA_COMPRA  DATE NOT NULL ,
	PRECIO_ULTIMA_COMPRA NUMBER(10) NOT NULL ,
CONSTRAINT  PKd_productos PRIMARY KEY (ID_PRODUCTO)
);


COMMENT ON TABLE D_PRODUCTOS IS 'Tabla con la lista de productos para la venta';


COMMENT ON COLUMN D_PRODUCTOS.ID_PRODUCTO IS 'Identificador de Productos';




COMMENT ON COLUMN D_PRODUCTOS.DESC_PRODUCTO IS 'Descripción del producto';




COMMENT ON COLUMN D_PRODUCTOS.COD_TIPO_PRODUCTO IS 'Código tipo producto';




COMMENT ON COLUMN D_PRODUCTOS.COD_TIPO_IVA IS 'Código de tipo de IVA';




COMMENT ON COLUMN D_PRODUCTOS.CODIGO_BARRA IS 'Código de barra, idientificador del producto';




COMMENT ON COLUMN D_PRODUCTOS.PORCENTAJE_BENEFICIO IS 'Porcentaje de beneficio. La utilidad a obtener se calcula sobre el precio_ultima_compra';




COMMENT ON COLUMN D_PRODUCTOS.DESC_ABREVIADO IS 'Descipcion abreviada del producto, se utiliza para imprimir en ticket';




COMMENT ON COLUMN D_PRODUCTOS.FECHA_ULTIMA_COMPRA IS 'Fecha de la última compra del producto';




COMMENT ON COLUMN D_PRODUCTOS.PRECIO_ULTIMA_COMPRA IS 'Precio de la última compra';



CREATE TABLE D_PRODUCTOS_MEDIDA_PRECIO
(	ID_REGISTRO          NUMBER(12) NOT NULL ,
	PRECIO_VENTA         NUMBER(10) NOT NULL ,
	ID_PRODUCTO          NUMBER(12) NOT NULL ,
	COD_MEDIDA           NUMBER(3) NOT NULL ,
	COD_SUCURSAL         NUMBER(2) NOT NULL ,
	COD_FORMA_PAGO       NUMBER(2) NOT NULL ,
CONSTRAINT  PK_d_productos_medida_precio PRIMARY KEY (ID_REGISTRO)
);



COMMENT ON TABLE D_PRODUCTOS_MEDIDA_PRECIO IS 'Relaciona la presentación del producto con el precio (Ej: Pack, unidad, caja)';




COMMENT ON COLUMN D_PRODUCTOS_MEDIDA_PRECIO.PRECIO_VENTA IS 'Precio de venta';




COMMENT ON COLUMN D_PRODUCTOS_MEDIDA_PRECIO.ID_PRODUCTO IS 'Idententificador de producto';




COMMENT ON COLUMN D_PRODUCTOS_MEDIDA_PRECIO.COD_MEDIDA IS 'Código de medida';




COMMENT ON COLUMN D_PRODUCTOS_MEDIDA_PRECIO.COD_SUCURSAL IS 'Código de sucursal';




COMMENT ON COLUMN D_PRODUCTOS_MEDIDA_PRECIO.COD_FORMA_PAGO IS 'Código forma de pago';




COMMENT ON COLUMN D_PRODUCTOS_MEDIDA_PRECIO.ID_REGISTRO IS 'Identificador de registros, identity';



CREATE TABLE D_STOCK_SUCURSAL
(	COD_SUCURSAL         NUMBER(2) NOT NULL ,
	ID_PRODUCTO          NUMBER(12) NOT NULL ,
	CANTIDAD_EXISTENCIA  NUMBER(10,2) NOT NULL ,
	STOCK_MINIMO         NUMBER(10,2) NOT NULL ,
CONSTRAINT  PKd_stock_sucursal PRIMARY KEY (COD_SUCURSAL,ID_PRODUCTO)
);



COMMENT ON TABLE D_STOCK_SUCURSAL IS 'Tabla de Stock de Sucursales';




COMMENT ON COLUMN D_STOCK_SUCURSAL.ID_PRODUCTO IS 'Identificador de Productos';




COMMENT ON COLUMN D_STOCK_SUCURSAL.COD_SUCURSAL IS 'Código de Sucursal';




COMMENT ON COLUMN D_STOCK_SUCURSAL.CANTIDAD_EXISTENCIA IS 'Cantidad e existencia en stock';




COMMENT ON COLUMN D_STOCK_SUCURSAL.STOCK_MINIMO IS 'Cantidad mínima de producto a mantener en stock, antes de su reposición';



CREATE TABLE D_SUCURSAL
(
	COD_SUCURSAL         NUMBER(2) NOT NULL ,
	DESC_SUCURSAL        VARCHAR2(30) NOT NULL ,
CONSTRAINT  PKd_sucursal PRIMARY KEY (COD_SUCURSAL)
);



COMMENT ON TABLE D_SUCURSAL IS 'Tabla de Sucursales';




COMMENT ON COLUMN D_SUCURSAL.COD_SUCURSAL IS 'Código de Sucursal';




COMMENT ON COLUMN D_SUCURSAL.DESC_SUCURSAL IS 'Descripción de la Sucursal';



CREATE TABLE D_TIMBRADO
(
	NRO_TIMBRADO         NUMBER(12) NOT NULL ,
	ESTABLECIMIENTO      VARCHAR2(3) NOT NULL ,
	PUNTO_EXPEDICION     VARCHAR2(3) NOT NULL ,
	FECHA_DESDE_TIMBRADO DATE NOT NULL ,
	FECHA_HASTA_TIMBRADO DATE NOT NULL ,
	DESDE_NUMERO_FACTURA NUMBER(10) NOT NULL ,
	HASTA_NUMERO_FACTURA NUMBER(10) NOT NULL ,
	NUMERO_ACTUAL_FACTURA NUMBER(10) NOT NULL ,
CONSTRAINT  PKd_timbrado PRIMARY KEY (NRO_TIMBRADO)
);



COMMENT ON TABLE D_TIMBRADO IS 'Tabla de Timbrados.  Cada sucursal o establecimiento, y número de caja debe tener un nro. diferente de timbrado. Los datos de factura se compone de la siguiente manera: Establecimiento-punto de expedicion- numero_actual_factura rellenado de ceros a la izquierdo. Ejemplo  001-001-0000001';




COMMENT ON COLUMN D_TIMBRADO.NRO_TIMBRADO IS 'Nro de timbrado';




COMMENT ON COLUMN D_TIMBRADO.ESTABLECIMIENTO IS 'Información del establecimiento a imprimir en la numeracion de la factura';




COMMENT ON COLUMN D_TIMBRADO.FECHA_DESDE_TIMBRADO IS 'Fecha vigencia desde del Nro de timbrado';




COMMENT ON COLUMN D_TIMBRADO.FECHA_HASTA_TIMBRADO IS 'Fecha vigencia hasta del Nro de timbrado';




COMMENT ON COLUMN D_TIMBRADO.PUNTO_EXPEDICION IS 'Información del punto de expedición a imprimir en la numeracion de la factura';




COMMENT ON COLUMN D_TIMBRADO.DESDE_NUMERO_FACTURA IS 'Numero de factura desde a emitir del Nro de timbrado';




COMMENT ON COLUMN D_TIMBRADO.HASTA_NUMERO_FACTURA IS 'Numero de factura hasta a emitir del Nro de timbrado';




COMMENT ON COLUMN D_TIMBRADO.NUMERO_ACTUAL_FACTURA IS 'Numero de factura actual a emitir del Nro de timbrado';



CREATE TABLE D_TIPO_COMPROBANTE
(
	COD_TIPO_COMPROBANTE NUMBER(2) NOT NULL ,
	DESC_TIPO_COMPROBANTE VARCHAR2(40) NOT NULL ,
CONSTRAINT  PKd_tipo_comprobante PRIMARY KEY (COD_TIPO_COMPROBANTE)
);



COMMENT ON TABLE D_TIPO_COMPROBANTE IS 'Tabla de tipo de comprobante a emitir';




COMMENT ON COLUMN D_TIPO_COMPROBANTE.COD_TIPO_COMPROBANTE IS 'Código del tipo de comprobante';




COMMENT ON COLUMN D_TIPO_COMPROBANTE.DESC_TIPO_COMPROBANTE IS 'Descripción del tipo de comprobante';



CREATE TABLE D_TIPO_COMPROBANTE_SECUENCIA
(
	ANHO                 NUMBER(4) NOT NULL ,
	NRO_COMPROBANTE_ACTUAL NUMBER(10) NOT NULL ,
	COD_TIPO_COMPROBANTE NUMBER(2) NOT NULL ,
CONSTRAINT  PKd_tipo_comprobante_secuenci PRIMARY KEY (COD_TIPO_COMPROBANTE,ANHO)
);



COMMENT ON TABLE D_TIPO_COMPROBANTE_SECUENCIA IS 'Tabla de secueencia de tipo de compronte';




COMMENT ON COLUMN D_TIPO_COMPROBANTE_SECUENCIA.ANHO IS 'Año de emisón del tipo de comprobante';




COMMENT ON COLUMN D_TIPO_COMPROBANTE_SECUENCIA.NRO_COMPROBANTE_ACTUAL IS 'Ultimo numero emitido del comprobante en el año. El nro de comprobante se debe reinicar cada año.';




COMMENT ON COLUMN D_TIPO_COMPROBANTE_SECUENCIA.COD_TIPO_COMPROBANTE IS 'Código del tipo de comprobante';



CREATE TABLE D_TIPO_IVA
(
	COD_TIPO_IVA         NUMBER(3) NOT NULL ,
	DESC_TIPO_IVA        VARCHAR2(20) NOT NULL ,
	PORCENTAJE_IVA       NUMBER(3) NOT NULL ,
	DIVISOR_IVA_INCLUIDO NUMBER(5) NOT NULL ,
CONSTRAINT  PKd_tipo_iva PRIMARY KEY (COD_TIPO_IVA)
);



COMMENT ON TABLE D_TIPO_IVA IS 'Tabla de tipos de IVA';




COMMENT ON COLUMN D_TIPO_IVA.COD_TIPO_IVA IS 'Código de tipo de IVA';




COMMENT ON COLUMN D_TIPO_IVA.DESC_TIPO_IVA IS 'Descripcón del tipo de IVA';




COMMENT ON COLUMN D_TIPO_IVA.PORCENTAJE_IVA IS 'Porcentaje de IVA';




COMMENT ON COLUMN D_TIPO_IVA.DIVISOR_IVA_INCLUIDO IS 'Divisor para determinar Imponible sin IVA';



CREATE TABLE D_TIPO_PRODUCTO
(
	COD_TIPO_PRODUCTO    NUMBER(5) NOT NULL ,
	DESC_TIPO_PRODUCTO   VARCHAR2(40) NOT NULL ,
CONSTRAINT  PKd_tipo_producto PRIMARY KEY (COD_TIPO_PRODUCTO)
);



COMMENT ON TABLE D_TIPO_PRODUCTO IS 'Tipos de productos';




COMMENT ON COLUMN D_TIPO_PRODUCTO.COD_TIPO_PRODUCTO IS 'Código tipo producto';




COMMENT ON COLUMN D_TIPO_PRODUCTO.DESC_TIPO_PRODUCTO IS 'Descripcipon del tipo de producto';



CREATE TABLE D_USUARIOS
(
	ID_USUARIO           VARCHAR2(4) NOT NULL ,
	NOMBRE_USUARIO       VARCHAR2(20) NOT NULL ,
	ESTADO               NUMBER(1) NOT NULL ,
CONSTRAINT  PKd_usuarios PRIMARY KEY (ID_USUARIO)
);


COMMENT ON TABLE D_USUARIOS IS 'Tabla con la lista de usuarios del sistema';


COMMENT ON COLUMN D_USUARIOS.ID_USUARIO IS 'Identificador del Usuario del sistema';




COMMENT ON COLUMN D_USUARIOS.NOMBRE_USUARIO IS 'Nombre completo del usuario';




COMMENT ON COLUMN D_USUARIOS.ESTADO IS 'Estado activo o no del usuario. El valor uno, indica que usuario está activo';



ALTER TABLE D_BANCO_CUENTA
	ADD (CONSTRAINT R_15 FOREIGN KEY (COD_BANCO) REFERENCES D_BANCO (COD_BANCO));



ALTER TABLE D_CAJAS
	ADD (CONSTRAINT R_41 FOREIGN KEY (NRO_TIMBRADO) REFERENCES D_TIMBRADO (NRO_TIMBRADO));



ALTER TABLE D_DETALLE_OPERACIONES
	ADD (CONSTRAINT R_47 FOREIGN KEY (COD_TIPO_IVA) REFERENCES D_TIPO_IVA (COD_TIPO_IVA));



ALTER TABLE D_DETALLE_OPERACIONES
	ADD (CONSTRAINT R_54 FOREIGN KEY (ID_PRODUCTO) REFERENCES D_PRODUCTOS (ID_PRODUCTO));



ALTER TABLE D_DETALLE_OPERACIONES
	ADD (CONSTRAINT R_55 FOREIGN KEY (COD_MEDIDA) REFERENCES D_MEDIDA (COD_MEDIDA));



ALTER TABLE D_DETALLE_OPERACIONES
	ADD (CONSTRAINT R_56 FOREIGN KEY (ID_OPERACION) REFERENCES D_MOVIMIENTO_OPERACIONES (ID_OPERACION));



ALTER TABLE D_MOVIMIENTO_OPERACIONES
	ADD (CONSTRAINT R_6 FOREIGN KEY (COD_OPERACION) REFERENCES D_OPERACIONES (COD_OPERACION));



ALTER TABLE D_MOVIMIENTO_OPERACIONES
	ADD (CONSTRAINT R_7 FOREIGN KEY (ID_PERSONA) REFERENCES D_PERSONAS (ID_PERSONA));



ALTER TABLE D_MOVIMIENTO_OPERACIONES
	ADD (CONSTRAINT R_8 FOREIGN KEY (NRO_CAJA) REFERENCES D_CAJAS (NRO_CAJA));



ALTER TABLE D_MOVIMIENTO_OPERACIONES
	ADD (CONSTRAINT R_10 FOREIGN KEY (ID_USUARIO) REFERENCES D_USUARIOS (ID_USUARIO));



ALTER TABLE D_MOVIMIENTO_OPERACIONES
	ADD (CONSTRAINT R_12 FOREIGN KEY (COD_TIPO_COMPROBANTE) REFERENCES D_TIPO_COMPROBANTE (COD_TIPO_COMPROBANTE));



ALTER TABLE D_MOVIMIENTO_OPERACIONES
	ADD (CONSTRAINT R_50 FOREIGN KEY (COD_SUCURSAL) REFERENCES D_SUCURSAL (COD_SUCURSAL));



ALTER TABLE D_PAGO_OPERACION
	ADD (CONSTRAINT R_46 FOREIGN KEY (COD_FORMA_PAGO) REFERENCES D_FORMA_PAGO (COD_FORMA_PAGO));



ALTER TABLE D_PAGO_OPERACION
	ADD (CONSTRAINT R_48 FOREIGN KEY (COD_BANCO) REFERENCES D_BANCO (COD_BANCO));



ALTER TABLE D_PAGO_OPERACION
	ADD (CONSTRAINT R_57 FOREIGN KEY (ID_OPERACION) REFERENCES D_MOVIMIENTO_OPERACIONES (ID_OPERACION));



ALTER TABLE D_PRODUCTOS
	ADD (CONSTRAINT R_2 FOREIGN KEY (COD_TIPO_PRODUCTO) REFERENCES D_TIPO_PRODUCTO (COD_TIPO_PRODUCTO));



ALTER TABLE D_PRODUCTOS
	ADD (CONSTRAINT R_3 FOREIGN KEY (COD_TIPO_IVA) REFERENCES D_TIPO_IVA (COD_TIPO_IVA));



ALTER TABLE D_PRODUCTOS_MEDIDA_PRECIO
	ADD (CONSTRAINT R_42 FOREIGN KEY (ID_PRODUCTO) REFERENCES D_PRODUCTOS (ID_PRODUCTO));



ALTER TABLE D_PRODUCTOS_MEDIDA_PRECIO
	ADD (CONSTRAINT R_43 FOREIGN KEY (COD_MEDIDA) REFERENCES D_MEDIDA (COD_MEDIDA));



ALTER TABLE D_PRODUCTOS_MEDIDA_PRECIO
	ADD (CONSTRAINT R_44 FOREIGN KEY (COD_SUCURSAL) REFERENCES D_SUCURSAL (COD_SUCURSAL));



ALTER TABLE D_PRODUCTOS_MEDIDA_PRECIO
	ADD (CONSTRAINT R_45 FOREIGN KEY (COD_FORMA_PAGO) REFERENCES D_FORMA_PAGO (COD_FORMA_PAGO));



ALTER TABLE D_STOCK_SUCURSAL
	ADD (CONSTRAINT R_4 FOREIGN KEY (ID_PRODUCTO) REFERENCES D_PRODUCTOS (ID_PRODUCTO));



ALTER TABLE D_STOCK_SUCURSAL
	ADD (CONSTRAINT R_5 FOREIGN KEY (COD_SUCURSAL) REFERENCES D_SUCURSAL (COD_SUCURSAL));



ALTER TABLE D_TIPO_COMPROBANTE_SECUENCIA
	ADD (CONSTRAINT R_35 FOREIGN KEY (COD_TIPO_COMPROBANTE) REFERENCES D_TIPO_COMPROBANTE (COD_TIPO_COMPROBANTE));


