CREATE TYPE T_ARTICULO AS OBJECT
(ID_ARTICULO NUMBER(8),
 NOMBRE_ARTICULO  VARCHAR2(40));
 /
CREATE TYPE TAB_ARTICULO IS TABLE OF T_ARTICULO;
/

CREATE TABLE PROVEEDORES
(ID_PROVEEDOR NUMBER(8),
 NOMBRE_PROVEEDOR VARCHAR2(100),
 ARTICULOS_PROVEIDOS TAB_ARTICULO)
NESTED TABLE ARTICULOS_PROVEIDOS STORE AS NESTED_ART; 

CREATE OR REPLACE PROCEDURE P_POBLAR_PROVEEDORES IS
 CURSOR C_PROV IS 
  SELECT P.ID,  P.NOMBRE ||', '||P.APELLIDO NOMBRE_PROVEEDOR
  FROM B_PERSONAS P
  WHERE P.ES_PROVEEDOR = 'S'
  AND   EXISTS (SELECT 'X' FROM B_COMPRAS WHERE ID_PROVEEDOR = P.ID);
 CURSOR C_ART(PPROV NUMBER) IS
   SELECT DISTINCT D.ID_ARTICULO, A.NOMBRE
   FROM   B_DETALLE_COMPRAS D JOIN B_COMPRAS C
   ON     C.ID = D.ID_COMPRA 
   JOIN   B_ARTICULOS A
   ON     A.ID = D.ID_ARTICULO
   WHERE  C.ID_PROVEEDOR = PPROV;
  VAR  TAB_ARTICULO := TAB_ARTICULO();
  IND  NUMBER;
 BEGIN
   FOR REG IN C_PROV LOOP
       IND := 0;
	   VAR.DELETE;
       FOR REG_ART IN C_ART(REG.ID) LOOP
	       IND := IND + 1;
		   VAR.EXTEND;
           VAR(IND):= T_ARTICULO (REG_ART.ID_ARTICULO, REG_ART.NOMBRE);		   
	   END LOOP;
	   INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE_PROVEEDOR, ARTICULOS_PROVEIDOS)
	   VALUES (REG.ID, REG.NOMBRE_PROVEEDOR, VAR); 
   END LOOP;
   COMMIT;
 END;
 /
 SELECT P.ID_PROVEEDOR, P.NOMBRE_PROVEEDOR, A.*
 FROM  PROVEEDORES P, TABLE(P.ARTICULOS_PROVEIDOS) A